runtime: python37

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
  secure: always

# Redirect /docs to documentation.
- url: /docs(\/?)
  static_files: build/docs/overview.html
  upload: build/docs/overview.html
  secure: always

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
  secure: always
