apiVersion: v1
data:
  liftbridge.yaml: |
    listen: 0.0.0.0:9292
    logging.level: debug

    nats.servers:
      - "nats://nats.liftbridge.svc:4222"

    clustering.min.insync.replicas: 1
kind: ConfigMap
metadata:
  labels:
    app: liftbridge
    component: config
    environment: dev
    k8s-app: liftbridge
  name: config
